export const GAME = {
  CREATE: 'GAME/CREATE',
  START: 'GAME/START',
  NEW_PLAYER: 'GAME/NEW_PLAYER',
  PHASE_DIVIDE_DECK: 'GAME/PHASE_DIVIDE_DECK',
  PHASE_DUEL: 'GAME/PHASE_DUEL',
  END_GAME: 'GAME/END_GAME',
}