export const PLAYER = {
  JOIN: 'PLAYER/JOIN',
  LEAVE: 'PLAYER/LEAVE',
  CHANGE_HOST: 'PLAYER/CHANGE_HOST',
  DRAW_CARD: 'PLAYER/DRAW_CARD',
  HOLD: 'PLAYER/HOLD',
  DUEL: 'PLAYER/DUEL',
  SHOW_CARD: 'PLAYER/SHOW_CARD',
  SHOW_HAND: 'PLAYER/SHOW_HAND',
  SHUFFLE_DECK: 'PLAYER/SHUFFLE_DECK',
  STATUS: 'PLAYER/STATUS'
}