export const USER_TYPE = {
  AUTH: {
    REGISTER: 'AUTH/REGISTER',
    LOGIN: 'AUTH/LOGIN',
    LOGOUT: 'AUTH/LOGOUT',
    VERIFY: 'AUTH/VERIFY'
  },
  DELETE: 'USER/DELETE',
  GET: 'USER/GET_INFO',
  UPDATE: 'USER/UPDATE'
}

export const ERROR = {
  NOT_EXIST: 'ERROR/NOT_EXIST',
  DUPLICATE: 'ERROR/DUPLICATE',
  UPDATE:'ERROR/UPDATE'
}

export const EVENT = {
  RUNNING: 'RUNNING',
  RESULT: 'RESET_RESULT'
}