const GAME_TYPES = {
  GAME: {
    JOIN: 'JOIN_ROOM',
    NEW_PLAYER: 'NEW_PLAYER',
    START: 'START_GAME',
    BEGIN: 'BEGIN_GAME',
    NEW_QUESTION: 'NEW_QUESTION',
    NEXT_QUESTION: 'NEXT_QUESTION',
    END: 'END_GAME',
    LEAVE: 'LEAVE_ROOM',
    KICK: 'KICK_PLAYER',
    ANSWER: 'ANSWER_QUEST',
    SCOREBOARD: 'SCORE_BOARD',
    TIMEOUT: 'QUEST_TIMEOUT',
    CORRECT_ANSWER: 'QUEST_CORRECT_ANSWER',
  },
  STATUS: {
    RESET: 'GAME/RESET_STATUS',
    SUCCESS: 'GAME/SUCCESS',
    FAIL: 'GAME/FAIL',
  },
  ERROR: {
    WRONG_CODE: 'WRONG_CODE',
    DUPLICATE: 'DUPLICATE',
    NOT_EXIST: 'NOT_EXIST',
    UNAUTHORIZED: 'UNAUTHORIZED',
  },
}
export default GAME_TYPES
